// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bloodtest_analytics.proto

// Protobuf Java Version: 3.25.5
package edu.rutmiit.demo.grpc;

public interface AnalyzeBloodTestRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bloodtestanalytics.AnalyzeBloodTestRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 bloodtest_id = 1;</code>
   * @return The bloodtestId.
   */
  long getBloodtestId();

  /**
   * <code>string gender = 2;</code>
   * @return The gender.
   */
  java.lang.String getGender();
  /**
   * <code>string gender = 2;</code>
   * @return The bytes for gender.
   */
  com.google.protobuf.ByteString
      getGenderBytes();

  /**
   * <code>int32 gemoglobin = 3;</code>
   * @return The gemoglobin.
   */
  int getGemoglobin();

  /**
   * <code>int32 eritrozit = 4;</code>
   * @return The eritrozit.
   */
  int getEritrozit();

  /**
   * <code>int32 trombozit = 5;</code>
   * @return The trombozit.
   */
  int getTrombozit();

  /**
   * <code>int32 leikozit = 6;</code>
   * @return The leikozit.
   */
  int getLeikozit();

  /**
   * <code>int32 palochloyader = 7;</code>
   * @return The palochloyader.
   */
  int getPalochloyader();

  /**
   * <code>int32 segmentoyader = 8;</code>
   * @return The segmentoyader.
   */
  int getSegmentoyader();

  /**
   * <code>int32 bazophil = 9;</code>
   * @return The bazophil.
   */
  int getBazophil();

  /**
   * <code>int32 limphozit = 10;</code>
   * @return The limphozit.
   */
  int getLimphozit();
}
