// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bloodtest_analytics.proto

// Protobuf Java Version: 3.25.5
package edu.rutmiit.demo.grpc;

public interface BloodTestAnalysisResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bloodtestanalytics.BloodTestAnalysisResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID теста (echo back)
   * </pre>
   *
   * <code>int64 blood_test_id = 1;</code>
   * @return The bloodTestId.
   */
  long getBloodTestId();

  /**
   * <pre>
   * Оценка, когда пересдать анализ (в неделях)
   * </pre>
   *
   * <code>int32 retest_advice = 2;</code>
   * @return The retestAdvice.
   */
  int getRetestAdvice();

  /**
   * <pre>
   * Уровень действия пациента: NONE, CONSULT, URGENT
   * </pre>
   *
   * <code>string action_level = 3;</code>
   * @return The actionLevel.
   */
  java.lang.String getActionLevel();
  /**
   * <pre>
   * Уровень действия пациента: NONE, CONSULT, URGENT
   * </pre>
   *
   * <code>string action_level = 3;</code>
   * @return The bytes for actionLevel.
   */
  com.google.protobuf.ByteString
      getActionLevelBytes();

  /**
   * <pre>
   * Оценка всех показателей в общем (0.0 — 10.0)
   * </pre>
   *
   * <code>double score_test = 4;</code>
   * @return The scoreTest.
   */
  double getScoreTest();
}
